"""
PSI Distilled Intelligence Model (Teacher-Student Pipeline)
This module acts as the "Student" model that learns from the large LLM "Teacher".
It uses scikit-learn for fast, cheap inference on resume scoring.
"""
import sqlite3
import json
import logging
from typing import Dict, Any
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestRegressor
import numpy as np

logger = logging.getLogger(__name__)

class StudentModel:
    def __init__(self, db_path: str = "telemetry.db"):
        self.db_path = db_path
        self.vectorizer = TfidfVectorizer(max_features=1000, stop_words="english")
        self.model = RandomForestRegressor(n_estimators=100, random_state=42)
        self.is_trained = False

    def load_teacher_data(self) -> tuple:
        """Extracts outputs generated by the Teacher LLM from the local database."""
        try:
            conn = sqlite3.connect(self.db_path)
            cursor = conn.cursor()
            # We look for historical runs to train on
            cursor.execute("SELECT details FROM analysis_runs")
            rows = cursor.fetchall()
            
            X_text = []
            y_score = []
            
            for row in rows:
                try:
                    data = json.loads(row[0])
                    # Reconstruct the raw text or structured skills as the training feature
                    skills = data.get("resume_parsed", {}).get("skills", [])
                    experience = data.get("resume_parsed", {}).get("experience", [])
                    
                    text_blob = " ".join(skills) + " " + " ".join([exp.get("description", "") for exp in experience])
                    score = data.get("match_score", 0.0)
                    
                    if text_blob.strip():
                        X_text.append(text_blob)
                        y_score.append(score)
                except Exception:
                    continue
                    
            return X_text, y_score
        except Exception as e:
            logger.error(f"Failed to load Teacher data: {e}")
            return [], []

    def train_student(self):
        """Trains the internal RandomForest on the Teacher's outputs."""
        logger.info("Initializing Teacher-Student Distillation...")
        X_text, y_score = self.load_teacher_data()
        
        if len(X_text) < 5:
            logger.warning("Insufficient Teacher data to train Student model. Need at least 5 examples.")
            return False
            
        X_vec = self.vectorizer.fit_transform(X_text)
        self.model.fit(X_vec, y_score)
        self.is_trained = True
        logger.info(f"Student Model successfully trained on {len(X_text)} resumes.")
        return True

    def predict_fast_score(self, parsed_resume: Dict[str, Any]) -> float:
        """Uses the Student model for fast, cheap inference."""
        if not self.is_trained:
            logger.warning("Student Model is not trained. Falling back to heuristic.")
            return 50.0
            
        skills = parsed_resume.get("skills", [])
        experience = parsed_resume.get("experience", [])
        text_blob = " ".join(skills) + " " + " ".join([exp.get("description", "") for exp in experience])
        
        if not text_blob.strip():
            return 0.0
            
        X_vec = self.vectorizer.transform([text_blob])
        pred_score = self.model.predict(X_vec)[0]
        return float(np.clip(pred_score, 0, 100))

# Global singleton
psi_student = StudentModel()
