from typing import TypedDict, List, Dict, Any, Optional

class InterviewState(TypedDict, total=False):
    """LangGraph shared state for the Cognitive Interview Session."""
    
    # ── Session Context ──
    session_id: str
    resume_text: str
    jd_text: str
    interview_focus: str
    
    # ── Pre-computation ──
    knowledge_graph: Dict[str, Any]      # Candidate's concepts (Projects, Skills)
    interview_tree: List[str]            # High-level planned topics
    
    # ── Real-Time Conversation ──
    messages: List[Dict[str, str]]       # Transcript: [{"role": "ai", "content": "..."}, {"role": "human", "content": "..."}]
    current_topic: str
    difficulty_level: int                # 1 to 10 scale (adaptive)
    
    # ── Proctoring & Compliance ──
    proctoring_alerts: List[Dict[str, Any]]  # E.g., [{"type": "tab_switch", "timestamp": "...", "confidence": 1.0}]
    cheating_probability: float              # 0.0 to 1.0
    
    # ── Evaluation ──
    evaluations: List[Dict[str, Any]]    # Per-answer scores (STAR, Technical, Communication)
    reasoning_paths: List[Dict[str, Any]] # Storage for Test-Time Scaling candidate paths
    final_report: Dict[str, Any]         # Generated by Hiring Committee at the end
    
    # ── Meta ──
    error: Optional[str]
    is_complete: bool                    # Flag to end interview
